### Inversa unei matrice

In [1]:
import numpy as np

In [18]:
def inverse(A):
    n = len(A)
    A_ext = np.concatenate((A, np.identity(3)), axis=1)
    for j in range(n):
        A_ext[j] /= A_ext[j, j]
        for i in range(n):
            if i == j:
                continue
            A_ext[i] -= A_ext[i, j] * A_ext[j]
    return A_ext[:, n:]

In [19]:
A = np.array([[1., 0., 0.],
              [0., 7., 0.],
              [0., 0., 1.]])

In [20]:
A_ = inverse(A)
A_

array([[1.        , 0.        , 0.        ],
       [0.        , 0.14285714, 0.        ],
       [0.        , 0.        , 1.        ]])

### Lema substitutiei

inlocuim coloana a 2-a cu c

In [21]:
c = [[7.], [1.], [7.]]
y = A_ @ c
eta = [-y[0][0] / y[1][0], 1 / y[1][0], -y[2][0] / y[1][0]]
Ek = np.array([[1, eta[0], 0],
               [0, eta[1], 0],
               [0, eta[2], 1]])
print(eta)
print('Ek(eta):')
print(Ek)

[-49.0, 7.0, -49.0]
Ek(eta):
[[  1. -49.   0.]
 [  0.   7.   0.]
 [  0. -49.   1.]]


In [22]:
A2 = np.array([[1., 7., 0.],
               [0., 1., 0.],
               [0., 7., 1.]])
print('Inversa lui A2:')
print(inverse(A2))

A2_ = Ek @ A_
print('Inversa cu lema substitutiei:')
print(A2_)

Inversa lui A2:
[[ 1. -7.  0.]
 [ 0.  1.  0.]
 [ 0. -7.  1.]]
Inversa cu lema substitutiei:
[[ 1. -7.  0.]
 [ 0.  1.  0.]
 [ 0. -7.  1.]]
