In [2]:
import numpy as np

In [26]:
# A = np.array([[1., 0., 0., 0.],
#               [1., 0.524, 0.274, 0.144],
#               [1., 1.047, 1.097, 1.148],
#               [1., 1.57, 2.467, 3.876]])
# b = np.array([[1],
#               [0.866],
#               [0.5],
#               [0]])
A = np.array([[1., 1., 5.],
               [2., 17., 20.],
               [2., 7., 13.]])
b = np.array([[4.],
               [33.],
               [16.]])

In [29]:
def gauss():
    if abs(np.linalg.det(A)) < 1e-15:
        print('determinantul e 0')
        return np.array([])
    n = A.shape[0]
    for k in range(n-1):
        print(A)
        for l in range(k+1, n):
            A[l] = A[l] - (A[l,k] / A[k,k]) * A[k]
    return A

In [30]:
gauss()

# x = np.zeros((4,1))

# for i in range(3, -1, -1):
#     x[i,0] = (b[i] - U[i,i+1:]@x[i+1:]) / U[i,i]

# print(x)

[[ 1.  1.  5.]
 [ 2. 17. 20.]
 [ 2.  7. 13.]]
[[ 1.  1.  5.]
 [ 0. 15. 10.]
 [ 0.  5.  3.]]


array([[ 1.        ,  1.        ,  5.        ],
       [ 0.        , 15.        , 10.        ],
       [ 0.        ,  0.        , -0.33333333]])

In [159]:
def gauss2(A):
    if np.linalg.det(A) < 1e-15:
        print('determinantul e 0')
        return np.array([])
    n = A.shape[0]
    for k in range(n-1):
        A[k+1:,k:] = A[k+1:,k:] - np.outer(A[k+1:,k] / A[k,k], [A[k,k:]])
    return A

In [160]:
gauss2(A)

array([[ 2, -1, -2],
       [ 0,  4,  4],
       [ 0,  0,  1]])

In [164]:
U = gauss2(A)
n = len(b)
if abs(np.linalg.det(U)) < 1e-15:
    print('det 0')
else:
    x = np.array([[float('nan')] for  _ in range(n)])
    for i in range(n - 1, -1, -1):
        x[i,0] = (b[i] - np.dot(U[i,i+1:], x[i+1:])) / U[i,i]
    print('x')
    print(x)

print('A * x = y')
print(np.dot(A, x))

x
[[-1.25]
 [ 4.5 ]
 [-3.  ]]
A * x = y
[[-1.]
 [ 6.]
 [-3.]]
